### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by buzard49** [coljac/netrunner-console#5]
After the last 2 ios updates it does not function properly. all of the Terminal Directive cards are in all lists. Even if I select only True Colors all the TD cards are in the list. And having issues with card art again.
Nice app but Apple keeps messing it up every update.

**Comment by coljac** [comment]
I think you're looking for this : [NetConsole](https://itunes.apple.com/us/app/netconsole-a-card-browser-for-android-netrunner/id933546332?mt=8)
This is a different program, not for iOS.

**Comment by buzard49** [comment]
Sorry, too many consoles.

Sent from my Verizon 4G LTE Smartphone

----- Reply message -----
